<?xml version="1.0" encoding="UTF-8"?><testrun name="AList0Test" project="List" tests="101" started="101" failures="0" errors="6" ignored="0">
  <testsuite name="AList0Test" time="0.094">
    <testcase name="testSortSelect_0" classname="AList0Test" time="0.0"/>
    <testcase name="testSortSelect_1" classname="AList0Test" time="0.0"/>
    <testcase name="testSortSelect_2" classname="AList0Test" time="0.0"/>
    <testcase name="testDelStart_0" classname="AList0Test" time="0.0"/>
    <testcase name="testDelStart_1" classname="AList0Test" time="0.0"/>
    <testcase name="testDelStart_2" classname="AList0Test" time="0.0"/>
    <testcase name="testDelStart_many" classname="AList0Test" time="0.0"/>
    <testcase name="testDelStart_null" classname="AList0Test" time="0.062">
      <error>java.lang.Exception: Unexpected exception, expected&lt;java.lang.IllegalArgumentException&gt; but was&lt;java.lang.NegativeArraySizeException&gt;&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: java.lang.NegativeArraySizeException&#13;
	at AList0.delStart(AList0.java:102)&#13;
	at AList0Test.testDelStart_null(AList0Test.java:459)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)&#13;
	... 15 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testToArray_0" classname="AList0Test" time="0.0"/>
    <testcase name="testToArray_1" classname="AList0Test" time="0.0"/>
    <testcase name="testToArray_2" classname="AList0Test" time="0.0"/>
    <testcase name="testGet_many" classname="AList0Test" time="0.0"/>
    <testcase name="testGet_null" classname="AList0Test" time="0.001">
      <error>java.lang.Exception: Unexpected exception, expected&lt;java.lang.IllegalArgumentException&gt; but was&lt;java.lang.ArrayIndexOutOfBoundsException&gt;&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: java.lang.ArrayIndexOutOfBoundsException&#13;
	at AList0.get(AList0.java:159)&#13;
	at AList0Test.testGet_null(AList0Test.java:691)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)&#13;
	... 15 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testReverseHalf_many" classname="AList0Test" time="0.001"/>
    <testcase name="testReverseHalf_null" classname="AList0Test" time="0.001"/>
    <testcase name="testClear_many" classname="AList0Test" time="0.0"/>
    <testcase name="testClear_null" classname="AList0Test" time="0.0"/>
    <testcase name="testGet_0" classname="AList0Test" time="0.0"/>
    <testcase name="testGet_1" classname="AList0Test" time="0.0"/>
    <testcase name="testGet_2" classname="AList0Test" time="0.001"/>
    <testcase name="testSet_0" classname="AList0Test" time="0.0"/>
    <testcase name="testSet_1" classname="AList0Test" time="0.0"/>
    <testcase name="testSet_2" classname="AList0Test" time="0.001"/>
    <testcase name="testReverseHalf_0" classname="AList0Test" time="0.0"/>
    <testcase name="testReverseHalf_1" classname="AList0Test" time="0.0"/>
    <testcase name="testReverseHalf_2" classname="AList0Test" time="0.0"/>
    <testcase name="testAddPos_0exc" classname="AList0Test" time="0.001"/>
    <testcase name="testAddPos_many" classname="AList0Test" time="0.0"/>
    <testcase name="testAddPos_null" classname="AList0Test" time="0.001">
      <error>java.lang.Exception: Unexpected exception, expected&lt;java.lang.IllegalArgumentException&gt; but was&lt;java.lang.ArrayIndexOutOfBoundsException&gt;&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: java.lang.ArrayIndexOutOfBoundsException&#13;
	at AList0.addPos(AList0.java:84)&#13;
	at AList0Test.testAddPos_null(AList0Test.java:410)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)&#13;
	... 15 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testAddStart_0" classname="AList0Test" time="0.001"/>
    <testcase name="testAddStart_1" classname="AList0Test" time="0.0"/>
    <testcase name="testAddStart_2" classname="AList0Test" time="0.0"/>
    <testcase name="testMinInd_0" classname="AList0Test" time="0.0"/>
    <testcase name="testMinInd_1" classname="AList0Test" time="0.001"/>
    <testcase name="testMinInd_2" classname="AList0Test" time="0.0"/>
    <testcase name="testMaxElem_many" classname="AList0Test" time="0.0"/>
    <testcase name="testMaxElem_null" classname="AList0Test" time="0.001"/>
    <testcase name="testAddEnd_0" classname="AList0Test" time="0.0"/>
    <testcase name="testAddEnd_1" classname="AList0Test" time="0.0"/>
    <testcase name="testAddEnd_2" classname="AList0Test" time="0.0"/>
    <testcase name="testAddPos_0" classname="AList0Test" time="0.0"/>
    <testcase name="testAddPos_1" classname="AList0Test" time="0.001"/>
    <testcase name="testAddPos_2" classname="AList0Test" time="0.0"/>
    <testcase name="testToString_many" classname="AList0Test" time="0.001"/>
    <testcase name="testToString_null" classname="AList0Test" time="0.0"/>
    <testcase name="testMaxElem_0" classname="AList0Test" time="0.0"/>
    <testcase name="testMaxElem_1" classname="AList0Test" time="0.0"/>
    <testcase name="testMaxElem_2" classname="AList0Test" time="0.001"/>
    <testcase name="testReverseHalf_manyOdd" classname="AList0Test" time="0.0"/>
    <testcase name="testMinElem_many" classname="AList0Test" time="0.0"/>
    <testcase name="testMinElem_null" classname="AList0Test" time="0.001"/>
    <testcase name="testAddEnd_many" classname="AList0Test" time="0.0"/>
    <testcase name="testAddEnd_null" classname="AList0Test" time="0.0"/>
    <testcase name="testSet_manyExc" classname="AList0Test" time="0.0"/>
    <testcase name="testGet_manyExc" classname="AList0Test" time="0.001"/>
    <testcase name="testAddStart_many" classname="AList0Test" time="0.0"/>
    <testcase name="testAddStart_null" classname="AList0Test" time="0.0"/>
    <testcase name="testDelPos_manyExc" classname="AList0Test" time="0.0"/>
    <testcase name="testMinElem_0" classname="AList0Test" time="0.001"/>
    <testcase name="testMinElem_1" classname="AList0Test" time="0.0"/>
    <testcase name="testMinElem_2" classname="AList0Test" time="0.0"/>
    <testcase name="testClear_0" classname="AList0Test" time="0.001"/>
    <testcase name="testClear_1" classname="AList0Test" time="0.0"/>
    <testcase name="testClear_2" classname="AList0Test" time="0.0"/>
    <testcase name="testDelPos_many" classname="AList0Test" time="0.001"/>
    <testcase name="testDelPos_null" classname="AList0Test" time="0.0">
      <error>java.lang.Exception: Unexpected exception, expected&lt;java.lang.IllegalArgumentException&gt; but was&lt;java.lang.NegativeArraySizeException&gt;&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: java.lang.NegativeArraySizeException&#13;
	at AList0.delPos(AList0.java:134)&#13;
	at AList0Test.testDelPos_null(AList0Test.java:570)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)&#13;
	... 15 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testAddPos_11" classname="AList0Test" time="0.0"/>
    <testcase name="testMinInd_many" classname="AList0Test" time="0.0"/>
    <testcase name="testMinInd_null" classname="AList0Test" time="0.001"/>
    <testcase name="testReverse_many" classname="AList0Test" time="0.0"/>
    <testcase name="testReverse_null" classname="AList0Test" time="0.0"/>
    <testcase name="testReverse_0" classname="AList0Test" time="0.0"/>
    <testcase name="testReverse_1" classname="AList0Test" time="0.001"/>
    <testcase name="testReverse_2" classname="AList0Test" time="0.0"/>
    <testcase name="testToString_0" classname="AList0Test" time="0.0"/>
    <testcase name="testToString_1" classname="AList0Test" time="0.001"/>
    <testcase name="testToString_2" classname="AList0Test" time="0.001"/>
    <testcase name="testMaxInd_0" classname="AList0Test" time="0.001"/>
    <testcase name="testMaxInd_1" classname="AList0Test" time="0.0"/>
    <testcase name="testMaxInd_2" classname="AList0Test" time="0.0"/>
    <testcase name="testSize_many" classname="AList0Test" time="0.0"/>
    <testcase name="testSize_null" classname="AList0Test" time="0.0"/>
    <testcase name="testMaxInd_many" classname="AList0Test" time="0.001"/>
    <testcase name="testMaxInd_null" classname="AList0Test" time="0.0"/>
    <testcase name="testDelEnd_0" classname="AList0Test" time="0.0"/>
    <testcase name="testDelEnd_1" classname="AList0Test" time="0.001"/>
    <testcase name="testDelEnd_2" classname="AList0Test" time="0.0"/>
    <testcase name="testDelPos_0" classname="AList0Test" time="0.0"/>
    <testcase name="testDelPos_1" classname="AList0Test" time="0.0"/>
    <testcase name="testDelPos_2" classname="AList0Test" time="0.0"/>
    <testcase name="testDelEnd_many" classname="AList0Test" time="0.0"/>
    <testcase name="testDelEnd_null" classname="AList0Test" time="0.001">
      <error>java.lang.Exception: Unexpected exception, expected&lt;java.lang.IllegalArgumentException&gt; but was&lt;java.lang.NegativeArraySizeException&gt;&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: java.lang.NegativeArraySizeException&#13;
	at AList0.delEnd(AList0.java:118)&#13;
	at AList0Test.testDelEnd_null(AList0Test.java:508)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)&#13;
	... 15 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testSortSelect_many" classname="AList0Test" time="0.001"/>
    <testcase name="testSortSelect_null" classname="AList0Test" time="0.0"/>
    <testcase name="testSize_0" classname="AList0Test" time="0.0"/>
    <testcase name="testSize_1" classname="AList0Test" time="0.0"/>
    <testcase name="testSize_2" classname="AList0Test" time="0.001"/>
    <testcase name="testToArray_many" classname="AList0Test" time="0.0"/>
    <testcase name="testToArray_null" classname="AList0Test" time="0.0"/>
    <testcase name="testSet_many" classname="AList0Test" time="0.0"/>
    <testcase name="testSet_null" classname="AList0Test" time="0.001">
      <error>java.lang.Exception: Unexpected exception, expected&lt;java.lang.IllegalArgumentException&gt; but was&lt;java.lang.ArrayIndexOutOfBoundsException&gt;&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: java.lang.ArrayIndexOutOfBoundsException&#13;
	at AList0.set(AList0.java:152)&#13;
	at AList0Test.testSet_null(AList0Test.java:635)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)&#13;
	... 15 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
